### ISSUE TITLE
Insure that when interlock or feedhold is held down, the state of 'stoppedness' cannot be exited

### ISSUE THREAD

**Issue by RobMackie** [FabMo/FabMo-Engine#935] opened 2022-06-14 16:21 UTC

**Comment by kyle-kingsbury** [comment] 2022-06-14 21:37
Duplicate of https://github.com/FabMo/FabMo-Engine/issues/841. Closing 841.

**Comment by kyle-kingsbury** [comment] 2023-02-08 15:17
Fixed with https://github.com/FabMo/FabMo-Engine/pull/992.

**Closed by kyle-kingsbury** 2023-02-08 15:17 UTC
Labels: reproduce, severity_3_BugNeedsFixing, priority_1_Top, in_progress, User Story
