### ISSUE TITLE
Authorize: Spindle keeps spinning while dialog is on screen

### ISSUE THREAD

**Issue by kyle-kingsbury** [FabMo/FabMo-Engine#915] opened 2022-05-20 16:35 UTC
Since this is a safety feature, the spindle should not be running when the user is prompted for authorization.

**Comment by kyle-kingsbury** [comment] 2022-06-07 14:34
This may be acceptable behavior, need to discuss further.

**Comment by RobMackie** [comment] 2022-06-07 18:16
Possible variant is pause with feedhold parameter as opposed to pause with timer as we have now or pause with human prompt.

all 3 could coexist.

**Comment by RobMackie** [comment] 2022-10-25 21:20
investigate if still relevant

**Comment by RobMackie** [comment] 2023-04-28 20:11
We are going to depend on the user to write the file correctly. Bug closed as not a bug.

**Closed by RobMackie** 2023-04-28 20:11 UTC
Labels: junk, status_Deferred, Task, release_2_Consideration
